# Site settings
title: Abhijeet Singh's CV
description: Abhijeet Singh Shine CV
favicon: /assets/img/avatar.JPG
baseurl: https://shinesingh1994.github.io
url: https://shinesingh1994.github.io
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Abhijeet Singh
  title: Web Developer
  address: Ontario, Canada
  email: mailshine94@gmail.com
  link: http://shiningsingh.com
  weibo:
  github: shinesingh1994
  linkedin: singh1994
  twitter: abhijeet_shine
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow: 5196867
  workHistory:
    - work1:
      company: AI Hub - Durham College
      location: Oshawa, ON, Canada
      title: Research Assistant - AI
      started: 2018
      duration: (2018 - Present)
      description: Designing Artificial Intelligence(AI) solutions and systems for clients - Coding and development of models and frameworks - Implementation of Machine Learning in native mobile applications - Regular consultation of and briefing sessions with clients - Working with project-based teams - General project management responsibilities
    - work2:
      company: Times Internet Ltd.
      location: India
      title: Software Developer
      started: 2015
      duration: (2015 - 2018)
      description: Worked on the leading portal The Economics Times (www.economictimes.com) - Skill Set - Core Skills – Javascript | HTML | CSS - Javascript Libraries – jQuery | Angular(2+) | ReactJS | Express | Node Platform  - CSS Preprocessors / Frameworks – Bootstrap  - Data Visualization – Google Charts  - Build Tools – Webpack - Versioning Tools – Git  - Backend Environments – XSLT | NodeJS - Optimization Tools – GTmetrix | Google  - Other Tools Used – Photoshop | Sublime | Visual Studio Code | Zeplin | MySQL
    - work3:
      company: CERT India, Government of Communications & IT
      location: India
      title: Internship
      started: 2014
      duration: (2014 - 2014)
      description: Developed a Web Application in C# - Automated Email Header Analysis - Used to check cyber crimes by tracing spam mailers.
  educationHistory:
    - education1:
      organization: Guru Gobind Singh Indraprastha University
      location: India
      degree: Bachelor
      major: Information Technology
      started: 2011
      duration: (2011 - 2015)
      description: Event Head in Sports Meet, Program Coordinator at Annual Cultural Fest - Anugoonj, Discipline Head Coordinator in Anugoonj.
  languages:
    - language1:
      name: English
      proficiency: Professional
    - language2:
      name: Hindi
      proficiency: Native
  programmingSkills:
    - skill1:
      name: JavaScript
      percentage: 80%
    - skill2:
      name: React JS
      percentage: 70%
    - skill3:
      name: React Native
      percentage: 70%
    - skill4:
      name: Angular
      percentage: 60%
    - skill5:
      name: HTML
      percentage: 100%
    - skill6:
      name: CSS
      percentage: 100%
    - skill7:
      name: Bootstrap
      percentage: 60%
